x-common-volumes: &common-volumes
  - 'storage:/var/www/storage'
  - '.env:/var/www/.env'

x-transmorpher-app-image: &transmorpher-app-image cybexwebdev/transmorpher:chore-v2-route-naming-app
x-transmorpher-transcoder-image: &transmorpher-transcoder-image cybexwebdev/transmorpher:chore-v2-route-naming-transcoder

x-transmorpher-common: &transmorpher-common
  image: *transmorpher-app-image
  depends_on:
    transmorpher-mariadb:
      condition: service_healthy
    traefik:
      condition: service_started
  volumes:
    - 'transmorpher-storage:/var/www/storage'
    - './amigor/.env.transmorpher:/var/www/.env'
  networks:
    - traefik
    - internal

x-transmorpher-app-url: &transmorpher-app-url
  APP_URL: https://transmorpher.${PULLPREVIEW_PUBLIC_DNS}

services:
  app:
    container_name: ${COMPOSE_PROJECT_NAME}
    build:
      context: .
      dockerfile: amigor/docker/prod/Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
      traefik:
        condition: service_started
    environment:
      APP_URL: https://${PULLPREVIEW_PUBLIC_DNS}
      TRANSMORPHER_WEB_DELIVERY_BASE_URL: https://transmorpher.${PULLPREVIEW_PUBLIC_DNS}
      TRANSMORPHER_WEB_API_BASE_URL: https://transmorpher.${PULLPREVIEW_PUBLIC_DNS}/api
      CONTAINER_ROLE: web
    networks:
      - traefik
      - internal
    volumes: *common-volumes

  initialize:
    command: [ '/var/www/docker/prod/pullpreview.initialize.sh' ]
    build:
      context: .
      dockerfile: amigor/docker/prod/Dockerfile
    restart: 'on-failure'
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      PULLPREVIEW: true
      PULLPREVIEW_FIRST_RUN: ${PULLPREVIEW_FIRST_RUN}
    volumes: *common-volumes
    networks:
      - internal

  mariadb:
    image: 'mariadb:lts-noble'
    environment:
      MARIADB_DATABASE: '${DB_DATABASE}'
      MARIADB_USER: '${DB_USERNAME}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'
      MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mariadb:/var/lib/mysql'
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      retries: 3
      timeout: 5s

  ########################################################################## Transmorpher ##########################################################################

  transmorpher:
    <<: *transmorpher-common
    environment:
      <<: *transmorpher-app-url
      CONTAINER_ROLE: web

  transmorpher-worker-transcoding:
    <<: *transmorpher-common
    image: *transmorpher-transcoder-image
    environment:
      <<: *transmorpher-app-url
      CONTAINER_ROLE: worker
      SERVICE_INSTANCES: ${VIDEO_TRANSCODING_WORKERS_AMOUNT:-1}
      QUEUE: video-transcoding

  transmorpher-worker-client-notifications:
    <<: *transmorpher-common
    environment:
      <<: *transmorpher-app-url
      CONTAINER_ROLE: worker
      SERVICE_INSTANCES: 1
      QUEUE: client-notifications

  transmorpher-worker-email:
    <<: *transmorpher-common
    environment:
      <<: *transmorpher-app-url
      CONTAINER_ROLE: worker
      SERVICE_INSTANCES: 1
      QUEUE: email

  transmorpher-scheduler:
    <<: *transmorpher-common
    environment:
      <<: *transmorpher-app-url
      CONTAINER_ROLE: scheduler

  transmorpher-initialize:
    <<: *transmorpher-common
    command: [ '/var/www/docker/prod/pullpreview.initialize.sh' ]
    restart: 'on-failure'
    environment:
      <<: *transmorpher-app-url
      CLIENT_CONTAINER_NAME: ${COMPOSE_PROJECT_NAME}
      PULLPREVIEW: true
      PULLPREVIEW_FIRST_RUN: ${PULLPREVIEW_FIRST_RUN}
    networks:
      - internal

  transmorpher-mariadb:
    image: 'mariadb:lts-noble'
    environment:
      MARIADB_DATABASE: 'transmorpher'
      MARIADB_USER: 'transmorpher'
      MARIADB_PASSWORD: 'transmorpher'
      MARIADB_ROOT_PASSWORD: 'transmorpher'
    volumes:
      - 'transmorpher-mariadb:/var/lib/mysql'
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      retries: 3
      timeout: 5s

  ########################################################################## Traefik ##########################################################################

  traefik:
    image: traefik:mimolette
    ports:
      - '80:80'
      - '443:443'
    environment:
      TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE: false
      TRAEFIK_LOG: true
      TRAEFIK_LOG_FILEPATH: '/logs/traefik.log'
      TRAEFIK_LOG_LEVEL: DEBUG
      TRAEFIK_API: false
      TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION: true
      TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION_ACME_EMAIL: 'cloud@cybex-online.com'
      TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION_ACME_CASERVER: 'https://acme-v02.api.letsencrypt.org/directory'
      TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION_ACME_STORAGE: 'acme.json'
      TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION_ACME_HTTPCHALLENGE: true
      TRAEFIK_CERTIFICATESRESOLVERS_PRODUCTION_ACME_HTTPCHALLENGE_ENTRYPOINT: web
      TRAEFIK_ENTRYPOINTS_WEB: true
      TRAEFIK_ENTRYPOINTS_WEB_ADDRESS: ':80'
      TRAEFIK_ENTRYPOINTS_WEB_HTTP: true
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_TO: websecure
      TRAEFIK_ENTRYPOINTS_WEB_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME: https
      TRAEFIK_ENTRYPOINTS_WEBSECURE: true
      TRAEFIK_ENTRYPOINTS_WEBSECURE_ADDRESS: ':443'
      TRAEFIK_PROVIDERS_FILE: true
      TRAEFIK_PROVIDERS_FILE_FILENAME: /etc/traefik/pullpreview.traefik.yml
      TRAEFIK_PROVIDERS_FILE_WATCH: true
    volumes:
      - ./pullpreview.traefik.yml:/etc/traefik/pullpreview.traefik.yml:ro
      # Needs to be mounted so that it is synced to the server for use in the pre-script
      - ./pullpreview.traefik.template.yml:/pullpreview.traefik.template.yml:ro
      - ./amigor/storage/logs:/logs
      - ./.htpasswd:/.htpasswd:ro
    networks:
      - traefik

  ########################################################################## Networks & Volumes ##########################################################################

networks:
  internal:
    internal: true
  traefik:
    name: traefik

volumes:
  mariadb:
    driver: local
  transmorpher-mariadb:
    driver: local
  storage:
    driver: local
  transmorpher-storage:
    driver: local
