services:
  app:
    image: cybexwebdev/php-laravel:${DOCKER_PHP_VERSION:-8.4}-alpine-devtools
    depends_on:
      - mariadb
    environment:
      APP_ENV: staging
      CONTAINER_ROLE: web
    volumes:
      - './amigor:/var/www'
      - '.:/var/package'
      - '.env:/var/www/.env'
      - './dist:/var/www/public/vendor/transmorpher'
      # For .bash_history and similar
      - 'home:/home/www'
    networks:
      - shared
      - internal
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`transmorpher-amigor.test`)'
      - 'traefik.http.services.${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=80'

  mariadb:
    image: 'mariadb:lts-noble'
    environment:
      MARIADB_DATABASE: '${DB_DATABASE}'
      MARIADB_USER: '${DB_USERNAME}'
      MARIADB_PASSWORD: '${DB_PASSWORD}'
      MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mariadb:/var/lib/mysql'
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      retries: 3
      timeout: 5s

networks:
  internal:
    internal: true
  shared:
    external: true

volumes:
  mariadb:
    driver: local
  home:
    driver: local
