services:
    app:
        container_name: ${DOCKER_CONTAINER_NAME:-transmorpher-amigor}
        build:
            context: ./amigor/docker/${DOCKER_PHP_VERSION:-8.3}
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-${DOCKER_PHP_VERSION:-8.3}/app-transmorpher-amigor
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - './.env:/var/www/html/amigor/.env'
        networks:
            - shared
            - internal
        depends_on:
            - mysql
        labels:
            - 'traefik.enable=true'
            - 'traefik.http.routers.${DOCKER_CONTAINER_NAME:-transmorpher-amigor}.rule=Host(`${DOCKER_CONTAINER_DOMAIN:-transmorpher-amigor.test}`)'
            - 'traefik.http.services.${DOCKER_CONTAINER_NAME:-transmorpher-amigor}.loadbalancer.server.port=80'
    mysql:
        container_name: amigor-mysql-1
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'sail-mysql:/var/lib/mysql'
        networks:
            - internal
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    internal:
        internal: true
    shared:
        external: true
volumes:
    sail-mysql:
        driver: local
